# Generated by Django 3.2.5 on 2021-07-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='rut')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('nombreComp', models.CharField(max_length=40, verbose_name='Nombre completo')),
                ('telefono', models.CharField(max_length=9, verbose_name='Numero de telefono')),
                ('direccion', models.CharField(max_length=30, verbose_name='Direccion')),
                ('email', models.CharField(max_length=30, verbose_name='Email')),
                ('contrasenia', models.CharField(max_length=30, verbose_name='Contraseña')),
                ('pais', models.CharField(max_length=15, verbose_name='Pais')),
            ],
        ),
    ]
